<?php
include 'db.php';

if(isset($_POST['save']))
{
    $company_id = !empty($_POST['company_id']) ? $_POST['company_id'] : NULL;
    $generated_by = $_POST['generated_by'];
    $report_type = $_POST['report_type'];
    $filters = $_POST['filters'];
    $file_format = $_POST['file_format'];
    $file_path = $_POST['file_path'];
    $status = $_POST['status'];

    $stmt = $conn->prepare("INSERT INTO report_exports
    (company_id,generated_by,report_type,filters,file_format,file_path,status)
    VALUES(?,?,?,?,?,?,?)");

    $stmt->bind_param(
        "iisssss",
        $company_id,
        $generated_by,
        $report_type,
        $filters,
        $file_format,
        $file_path,
        $status
    );

    if($stmt->execute()){
        echo "<script>alert('Report Saved Successfully');</script>";
    }else{
        echo $conn->error;
    }
}
?>

<!DOCTYPE html>
<html>
<head>
<title>Add Report Export</title>

<style>

body{
    background:#f5f6fa;
    font-family:Arial;
}

.container{
    width:700px;
    margin:30px auto;
    background:#fff;
    padding:30px;
    border-radius:10px;
    box-shadow:0 0 10px #ddd;
}

h2{
    text-align:center;
}

label{
    font-weight:bold;
}

input,select,textarea{

    width:100%;
    padding:10px;
    margin-top:5px;
    margin-bottom:15px;
    border:1px solid #ccc;
    border-radius:5px;

}

button{

    background:#007bff;
    color:white;
    border:none;
    padding:12px 20px;
    cursor:pointer;
    border-radius:5px;

}

button:hover{
    background:#0056b3;
}

</style>

</head>

<body>

<div class="container">

<h2>Create Report Export</h2>

<form method="post">

<label>Company ID</label>
<input type="number" name="company_id">

<label>Generated By (User ID)</label>
<input type="number" name="generated_by" required>

<label>Report Type</label>
<input type="text" name="report_type" required>

<label>Filters (JSON)</label>

<textarea name="filters" rows="5">
{"department":"HR","date_from":"2025-01-01","date_to":"2025-01-31"}
</textarea>

<label>File Format</label>

<select name="file_format">
<option value="pdf">PDF</option>
<option value="excel">Excel</option>
<option value="csv">CSV</option>
</select>

<label>File Path</label>

<input type="text" name="file_path">

<label>Status</label>

<select name="status">

<option>Active</option>
<option>Inactive</option>
<option>Deleted</option>

</select>

<button type="submit" name="save">Save Report</button>

</form>

</div>

</body>
</html>