<?php
include 'db.php';

$result = $conn->query("SELECT * FROM report_exports ORDER BY id DESC");
?>

<!DOCTYPE html>

<html>

<head>

<title>Report Export List</title>

<style>

body{

font-family:Arial;
background:#f2f2f2;

}

table{

width:95%;
margin:30px auto;
border-collapse:collapse;
background:white;

}

th{

background:#007bff;
color:white;
padding:12px;

}

td{

padding:10px;
border:1px solid #ddd;
text-align:center;

}

tr:nth-child(even){

background:#f7f7f7;

}

a{

padding:5px 10px;
text-decoration:none;
border-radius:5px;
color:white;

}

.edit{

background:green;

}

.delete{

background:red;

}

</style>

</head>

<body>

<table>

<tr>

<th>ID</th>
<th>Company</th>
<th>Generated By</th>
<th>Report Type</th>
<th>Filters</th>
<th>Format</th>
<th>File</th>
<th>Status</th>
<th>Date</th>
<th>Action</th>

</tr>

<?php while($row=$result->fetch_assoc()){ ?>

<tr>

<td><?= $row['id']; ?></td>

<td><?= $row['company_id']; ?></td>

<td><?= $row['generated_by']; ?></td>

<td><?= $row['report_type']; ?></td>

<td><?= $row['filters']; ?></td>

<td><?= strtoupper($row['file_format']); ?></td>

<td><?= $row['file_path']; ?></td>

<td><?= $row['status']; ?></td>

<td><?= $row['created_at']; ?></td>

<td>

<a class="edit" href="edit_report.php?id=<?= $row['id'];?>">Edit</a>

<a class="delete"
onclick="return confirm('Delete?')"
href="delete_report.php?id=<?= $row['id'];?>">Delete</a>

</td>

</tr>

<?php } ?>

</table>

</body>

</html>