<?php
include 'db.php';

$id=$_GET['id'];

$data=$conn->query("SELECT * FROM report_exports WHERE id='$id'");
$row=$data->fetch_assoc();

if(isset($_POST['update'])){

$company=$_POST['company_id'];
$user=$_POST['generated_by'];
$type=$_POST['report_type'];
$filters=$_POST['filters'];
$format=$_POST['file_format'];
$file=$_POST['file_path'];
$status=$_POST['status'];

$stmt=$conn->prepare("UPDATE report_exports
SET
company_id=?,
generated_by=?,
report_type=?,
filters=?,
file_format=?,
file_path=?,
status=?
WHERE id=?");

$stmt->bind_param(
"iisssssi",
$company,
$user,
$type,
$filters,
$format,
$file,
$status,
$id
);

$stmt->execute();

header("Location: report_list.php");

}
?>

<!DOCTYPE html>

<html>

<head>

<title>Edit Report</title>

<style>

body{
font-family:Arial;
background:#eee;
}

.container{

width:700px;
margin:30px auto;
background:#fff;
padding:25px;
border-radius:8px;

}

input,select,textarea{

width:100%;
padding:10px;
margin:8px 0;

}

button{

padding:12px;
background:green;
color:white;
border:none;

}

</style>

</head>

<body>

<div class="container">

<h2>Edit Report</h2>

<form method="post">

Company ID

<input type="number"
name="company_id"
value="<?= $row['company_id'];?>">

Generated By

<input type="number"
name="generated_by"
value="<?= $row['generated_by'];?>">

Report Type

<input type="text"
name="report_type"
value="<?= $row['report_type'];?>">

Filters

<textarea name="filters"><?= $row['filters'];?></textarea>

File Format

<select name="file_format">

<option <?=($row['file_format']=='pdf')?'selected':'';?> value="pdf">PDF</option>

<option <?=($row['file_format']=='excel')?'selected':'';?> value="excel">Excel</option>

<option <?=($row['file_format']=='csv')?'selected':'';?> value="csv">CSV</option>

</select>

File Path

<input type="text"
name="file_path"
value="<?= $row['file_path'];?>">

Status

<select name="status">

<option <?=($row['status']=='Active')?'selected':'';?>>Active</option>

<option <?=($row['status']=='Inactive')?'selected':'';?>>Inactive</option>

<option <?=($row['status']=='Deleted')?'selected':'';?>>Deleted</option>

</select>

<button name="update">Update</button>

</form>

</div>

</body>

</html>